### ISSUE TITLE
new function (connection via proxy)

### ISSUE THREAD

**Issue by hamelsveld** [y-ken/fluent-plugin-twitter#27]
Can you please build a proxy config in the module? I need to be able to configure a proxy to acces the outside world.

**Comment by y-ken** [comment]
@okkez
Would you tell me are there any common proxy helper for fluentd?

**Comment by okkez** [comment]
Nothing, for now.
BTW twitter gem supports proxy functionality.
See https://github.com/sferik/twitter/blob/aa909b3b7733ca619d80f1c8cba961033d1fc7e6/examples/Configuration.md#using-a-proxy

**Comment by y-ken** [comment]
@hamelsveld It has implemented now. I'll release new version of gem in a few days.
