### ISSUE TITLE
Release new version for avoiding twitterstream gem problems.

### ISSUE THREAD

**Issue by repeatedly** [y-ken/fluent-plugin-twitter#34]
The master uses twitter gem instead of twitterstream.
Release new version, maybe 0.6?, is better for users.
twitterstream is unmaintained gem and it has a problem with ruby 2.4.

**Comment by y-ken** [comment]
Sure!

**Comment by y-ken** [comment]
I'm sorry for late. The new version as 0.6.0 has released now!
